### ISSUE TITLE
A bug in UTF8 string length

### ISSUE THREAD

**Issue by jmjeong** [seejohnrun/console_tweet#5]
Hi, 

I am a newbie in Ruby language.

According to ruby string manual, ruby string does not support utf-8 string.

In lib/console_tweet/cli.rb 86 line:

```
return failtown("Tweet is too long!") if tweet_text.size > 140
```

This line works good for english string, but is not good for UTF-8 string, especially for CJK language.
Twitter supports UTF-8 encoding for tweet, so length check routine should admire UTF-8 encoding.

**Comment by seejohnrun** [comment]
Released as part of 0.1.3 - thanks again :)
