### ISSUE TITLE
using tags in console_tweet

### ISSUE THREAD

**Issue by pietvanzoen** [seejohnrun/console_tweet#9]
Can't seem to use hash tags in console_tweet. I don't know ruby well but my guess is that it has something to do with hash/pound-sign being used for commenting.

Any thoughts?

**Comment by seejohnrun** [comment]
Try containing your tweet in single quotes.
Bash escapes # as a comment

**Comment by pietvanzoen** [comment]
That worked. Thanks!

**Comment by seejohnrun** [comment]
Any time!
